import Head from "next/head";
import { useEffect } from "react";

export default function Home({ bodyHtml, inlineStyles }) {
  useEffect(() => {
    // GSAP must load BEFORE Webflow scripts.
    // Webflow main JS calls ix2.init() the moment it loads.
    // If gsap is not on window yet, IX2 fails silently -> no animations.
    const SCRIPTS = [
      "/assets/jquery-3.5.1.min.dc5e7f18c8.js",
      "/assets/gsap.min.js",
      "/assets/SplitText.min.js",
      "/assets/ScrollTrigger.min.js",
      "/assets/lenis.js",
      "/assets/whitewolf.schunk1.js",
      "/assets/whitewolf.schunk2.js",
      "/assets/whitewolf.js",
    ];

    const afterAllLoaded = () => {
      // Register GSAP plugins
      try { gsap.registerPlugin(SplitText, ScrollTrigger); } catch (e) {}

      // Connect Lenis to ScrollTrigger.
      // Without this, Lenis intercepts scroll so ScrollTrigger never fires.
      try {
        const lenis = new Lenis({
          duration: 1.8,
          easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)),
          direction: "vertical",
          gestureDirection: "vertical",
          smooth: true,
          mouseMultiplier: 1,
          smoothTouch: false,
          touchMultiplier: 2,
          infinite: false,
        });
        lenis.on("scroll", ScrollTrigger.update);
        gsap.ticker.add((time) => { lenis.raf(time * 1000); });
        gsap.ticker.lagSmoothing(0);
      } catch (e) {}

      // Trigger Webflow ready cycle.
      // Webflow.ready() fires all registered module handlers (slider, navbar, ix2).
      // Do NOT call Webflow.destroy() - it clears the IX2 event queue.
      try {
        if (window.Webflow) {
          window.Webflow.ready();
        }
      } catch (e) {}
    };

    // Load scripts sequentially - each waits for the previous
    const loadNext = (index) => {
      if (index >= SCRIPTS.length) {
        afterAllLoaded();
        return;
      }
      if (document.querySelector('script[src="' + SCRIPTS[index] + '"]')) {
        loadNext(index + 1);
        return;
      }
      const s = document.createElement("script");
      s.src = SCRIPTS[index];
      s.type = "text/javascript";
      s.onload = () => loadNext(index + 1);
      s.onerror = () => loadNext(index + 1);
      document.body.appendChild(s);
    };

    loadNext(0);
  }, []);

  return (
    <>
      <Head>
        <title>White Wolf - Digital Transformation Agency</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style dangerouslySetInnerHTML={{ __html: inlineStyles }} />
      </Head>
      <div
        suppressHydrationWarning
        dangerouslySetInnerHTML={{ __html: bodyHtml }}
      />
    </>
  );
}

export async function getStaticProps() {
  // Import pre-processed HTML (generated by: node scripts/process-html.js)
  // This avoids reading the source HTML file at build time on Vercel.
  const { bodyHtml, inlineStyles } = require("../lib/processed-html.js");
  return { props: { bodyHtml, inlineStyles } };
}
